### ISSUE TITLE
Return address and l2 tx hash from deployFromL1

### ISSUE THREAD

**Issue by th3m477** [omurovec/foundry-zksync#11]
1. The alias method `deployFromL1` should return the counterfactual address
2. Both `deployFromL1` functions could also return the response from `requestL2Transaction`, which is the l2 tx hash.

**Comment by omurovec** [comment]
Fixed the deployment address return in this pr: https://github.com/omurovec/foundry-zksync-era/pull/8/files

The issue with returning the canonical transaction hash in both functions is that this is dependant on the timestamp during execution and the return value will never match the actual transaction hash. Unfortunately I don't believe there is any way to determine the correct transaction hash on L2 other than examining the L1 transaction after execution.

**Comment by th3m477** [comment]
you are correct - can only see post execution :(

Thanks for making this lib, very useful, having issues verifying contracts too (using web explorer) if any tips !

**Comment by omurovec** [comment]
Hmmm, verification might be a bit tricky and probably won't be possible through foundry but created a new issue to track it https://github.com/omurovec/foundry-zksync-era/issues/16
